/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id integer generated by default as identity primary key,
    name varchar(100),
    date_of_birth date,
    escape_attempts decimal(10,2),
    neutered boolean,
    weight_kg integer
);


                                     Table "public.animals"
     Column      |          Type          | Collation | Nullable |           Default
-----------------+------------------------+-----------+----------+------------------------------
 id              | integer                |           | not null | generated always as identity
 name            | character varying(100) |           |          |
 date_of_birth   | date                   |           |          |
 escape_attempts | numeric(10,2)          |           |          |
 neutered        | boolean                |           |          |
 weight_kg       | integer                |           |          |
