/* Database schema to keep the structure of entire database. */

 CREATE TABLE animals (
    id integer generated by default as identity primary key,
    name varchar(100),
    date_of_birth date,
    escape_attempts decimal(10,2),
    neutered boolean,
    weight_kg integer
);

ALTER TABLE animals
ADD COLUMN species_id INT,
ADD COLUMN owner_id INT;

CREATE TABLE owners (
    id  INT generated by default as identity primary key, 
    full_name VARCHAR(100), 
    age INT
);

CREATE TABLE species (
    id  INT generated by default as identity primary key,
    name VARCHAR(100)
);


CREATE TABLE owners (
    id  INT PRIMARY KEY,
    full_name VARCHAR(100),
    age INT
 );

CREATE TABLE species (
     id SERIAL PRIMARY KEY,
     name VARCHAR(100)
 );

ALTER TABLE animals
DROP COLUMN species;

ALTER TABLE animals
ADD CONSTRAINT fk_species_id
FOREIGN KEY (species_id) REFERENCES species(id);

ALTER TABLE animals
ADD CONSTRAINT fk_owner_id
FOREIGN KEY (owner_id) REFERENCES owners(id);
